In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [2]:
import torch

## Basic tensor operation

In [3]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.6507, 0.6818],
         [0.5185, 0.4999],
         [0.7623, 0.8741]],

        [[0.8672, 0.6571],
         [0.2684, 0.0842],
         [0.9717, 0.8058]],

        [[0.6070, 0.1313],
         [0.3620, 0.5863],
         [0.6626, 0.1264]],

        [[0.1038, 0.1960],
         [0.4850, 0.4981],
         [0.9896, 0.9008]]])

Display the size of the produced tensor

In [4]:
tensor.shape

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [5]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [6]:
reshaped = tensor.reshape(4,6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [7]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
tensor = torch.tensor(list_to_transform)
tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [8]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [9]:
y = x+3 
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [10]:
y = x*3 
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [11]:
y = x**3 
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [12]:
k = torch.Tensor([8, 7, 5, 1])
y = x*k 
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [13]:
y = x**k 
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [14]:
y = torch.exp(x) 
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [15]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b 
y

tensor([0.1140, 0.0911, 0.6217, 0.2829, 0.0443])

Perform the dot product of `a` and `b`

In [16]:
y = torch.dot(a,b) 
y

tensor(1.1539)

Sum along the column axis of `l`

In [17]:
l = torch.rand((5, 3, 6))
l.sum(dim=1)

tensor([[1.0285, 2.0006, 1.4773, 1.3422, 1.7112, 1.3854],
        [1.2510, 0.8872, 1.1168, 1.0493, 1.1654, 1.7721],
        [0.7491, 2.7748, 1.2751, 1.2449, 1.1441, 1.7620],
        [0.8277, 2.0583, 0.8725, 1.0484, 1.5696, 1.8828],
        [0.7761, 1.0546, 0.9216, 1.6555, 1.8057, 1.8743]])

## Slicing

Display the 3 last element of x

In [18]:
x[-3:]

tensor([1, 2, 3])

Display the last element of x

In [19]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [20]:
m = torch.arange(18)
for i in range(0, len(m), 2):
    print(m[i])

tensor(0)
tensor(2)
tensor(4)
tensor(6)
tensor(8)
tensor(10)
tensor(12)
tensor(14)
tensor(16)


Print only the first 2 rows of `matrix`

In [25]:
matrix = torch.rand((6, 4, 2))
matrix[:2]

tensor([[[0.0514, 0.5929],
         [0.1533, 0.1271],
         [0.4884, 0.8572],
         [0.5554, 0.9488]],

        [[0.3557, 0.7267],
         [0.8880, 0.1695],
         [0.0301, 0.6289],
         [0.5803, 0.4055]]])

Now, only print the first 2 columns of `matrix`

In [77]:
matrix[:,:2]

tensor([[[0.8441, 0.6147],
         [0.3558, 0.5355]],

        [[0.7166, 0.7620],
         [0.3182, 0.5334]],

        [[0.8303, 0.4398],
         [0.2046, 0.7993]],

        [[0.4043, 0.5283],
         [0.7541, 0.9731]],

        [[0.9207, 0.0405],
         [0.7838, 0.9419]],

        [[0.4247, 0.5259],
         [0.6356, 0.5151]]])