In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [2]:
import torch

## Basic tensor operation

In [3]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.1059, 0.9441],
         [0.2063, 0.8683],
         [0.9319, 0.3045]],

        [[0.6550, 0.8558],
         [0.6603, 0.8627],
         [0.6173, 0.1537]],

        [[0.9650, 0.3258],
         [0.2708, 0.4074],
         [0.6278, 0.1846]],

        [[0.2403, 0.4336],
         [0.0636, 0.4582],
         [0.7355, 0.4254]]])

Display the size of the produced tensor

In [4]:
#TODO
tensor.size()

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [5]:
#TODO
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [6]:
#reshaped = ...
#reshaped.shape

reshaped = tensor.reshape(4,6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [7]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
#TODO
tensor = torch.tensor(list_to_transform)
tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [8]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [9]:
y = x+3 #TODO
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [10]:
y = x*3 #TODO
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [11]:
y = x**3 #TODO
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [12]:
k = torch.Tensor([8, 7, 5, 1])
y = x*k #TODO
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [13]:
y = x**k #TODO
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [14]:
y = torch.exp(x) #TODO
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [15]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b #TODO
y

tensor([0.0210, 0.0106, 0.6544, 0.4566, 0.3979])

Perform the dot product of `a` and `b`

In [16]:
y = torch.dot(a,b) #TODO
y

tensor(1.5405)

Sum along the column axis of `l`

In [17]:
l = torch.rand((5, 3, 6))
l.sum(dim=1)
# TODO

tensor([[1.4928, 1.5933, 1.0870, 1.5878, 1.3960, 1.7891],
        [1.6834, 1.8830, 2.1170, 2.1544, 2.2069, 1.2199],
        [2.0964, 0.7398, 1.3684, 1.8156, 1.7349, 1.4339],
        [1.2747, 1.2666, 1.7812, 1.9716, 1.7872, 2.2744],
        [0.6172, 0.7775, 1.0306, 1.4084, 1.6767, 1.5904]])

## Slicing

Display the 3 last element of x

In [27]:
#TODO
x[-3:]

tensor([1, 2, 3])

Display the last element of x

In [28]:
#TODO
x[-1]

tensor(3)

Display the element of m, by step of 2

In [29]:
m = torch.arange(18)

#TODO

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

Print only the first 2 rows of `matrix`

In [36]:
matrix = torch.rand((6, 4, 2))
matrix[:2]
#TODO

tensor([[[0.1149, 0.6332],
         [0.4951, 0.8050],
         [0.3876, 0.0142],
         [0.0379, 0.3304]],

        [[0.6780, 0.4512],
         [0.7612, 0.3307],
         [0.4951, 0.6101],
         [0.2857, 0.6401]]])

Now, only print the first 2 columns of `matrix`

In [32]:
#TODO
matrix[:,:2]

tensor([[[0.7416, 0.7293],
         [0.8908, 0.8563]],

        [[0.6196, 0.4894],
         [0.0939, 0.0741]],

        [[0.2893, 0.6230],
         [0.6322, 0.9064]],

        [[0.1811, 0.1951],
         [0.4241, 0.5507]],

        [[0.8193, 0.9967],
         [0.4626, 0.6684]],

        [[0.1633, 0.6803],
         [0.8969, 0.4083]]])