In this notebook, you will learn how to manipulate data with Pytorch  
Let's start by importing Pytorch

In [57]:
import torch

## Basic tensor operation

In [58]:
tensor = torch.rand((4, 3, 2))
tensor

tensor([[[0.8379, 0.2164],
         [0.2960, 0.0871],
         [0.4393, 0.4849]],

        [[0.2786, 0.1438],
         [0.0385, 0.5041],
         [0.2801, 0.2309]],

        [[0.9897, 0.4829],
         [0.1682, 0.4753],
         [0.2111, 0.6636]],

        [[0.8556, 0.7035],
         [0.2136, 0.3063],
         [0.1652, 0.9674]]])

Display the size of the produced tensor

In [59]:
tensor.shape

torch.Size([4, 3, 2])

Give the total number of elements inside the tensor

In [60]:
tensor.numel()

24

Change the shape of the tensor into a 4x6 tensor

In [61]:
reshaped = tensor.reshape(4,6)
reshaped.shape

torch.Size([4, 6])

Transform a python list into a tensor

In [62]:
list_to_transform = [[9, 8, 7], [4, 5, 6], [3, 2, 1]]
tensor = torch.tensor(list_to_transform)
tensor

tensor([[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]])

## Operations on tensor

In [63]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

Add 3 to every element of the tensor, put the result in a new tensor

In [64]:
y = x+3 
y

tensor([3, 4, 5, 6])

Multiply by 3 the tensor x, put the result in a new tensor

In [65]:
y = x*3 
y

tensor([0, 3, 6, 9])

Put every element of x to the power of 3

In [66]:
y = x**3 
y

tensor([ 0,  1,  8, 27])

Multiply x with k

In [67]:
k = torch.Tensor([8, 7, 5, 1])
y = x*k 
y

tensor([ 0.,  7., 10.,  3.])

Makes x to the power of k

In [68]:
y = x**k 
y

tensor([ 0.,  1., 32.,  3.])

Put every element of x to exponential

In [69]:
y = torch.exp(x) 
y

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

Perform the element wise product of `a` and `b`

In [70]:
a = torch.rand((5))
b = torch.rand((5))
y = a * b 
y

tensor([0.1946, 0.3530, 0.1222, 0.5783, 0.0484])

Perform the dot product of `a` and `b`

In [71]:
y = torch.dot(a,b) 
y

tensor(1.2965)

Sum along the column axis of `l`

In [72]:
l = torch.rand((5, 3, 6))
l.sum(dim=1)

tensor([[1.8801, 0.5380, 2.4555, 2.2886, 1.7278, 2.6035],
        [1.0294, 1.8961, 2.2521, 2.0795, 1.5783, 2.6952],
        [1.6601, 0.3149, 1.3806, 1.4365, 0.5016, 0.6661],
        [1.3067, 1.9910, 1.5839, 1.9851, 2.2945, 1.2326],
        [1.4964, 0.9095, 1.5154, 1.6971, 1.1677, 1.6934]])

## Slicing

Display the 3 last element of x

In [73]:
x[-3:]

tensor([1, 2, 3])

Display the last element of x

In [74]:
x[-1]

tensor(3)

Display the element of m, by step of 2

In [75]:
m = torch.arange(18)
for i in range(0, len(m), 2):
    print(m[i])

tensor(0)
tensor(2)
tensor(4)
tensor(6)
tensor(8)
tensor(10)
tensor(12)
tensor(14)
tensor(16)


Print only the first 2 rows of `matrix`

In [76]:
matrix = torch.rand((6, 4, 2))
matrix[:2]

tensor([[[0.8441, 0.6147],
         [0.3558, 0.5355],
         [0.2220, 0.9912],
         [0.4356, 0.7801]],

        [[0.7166, 0.7620],
         [0.3182, 0.5334],
         [0.0145, 0.5580],
         [0.6615, 0.9774]]])

Now, only print the first 2 columns of `matrix`

In [77]:
matrix[:,:2]

tensor([[[0.8441, 0.6147],
         [0.3558, 0.5355]],

        [[0.7166, 0.7620],
         [0.3182, 0.5334]],

        [[0.8303, 0.4398],
         [0.2046, 0.7993]],

        [[0.4043, 0.5283],
         [0.7541, 0.9731]],

        [[0.9207, 0.0405],
         [0.7838, 0.9419]],

        [[0.4247, 0.5259],
         [0.6356, 0.5151]]])